name: Merge plugin-only PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review
      - synchronize
  check_suite:
    types:
      - completed

  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false

# permissions:
#   checks: read
#   contents: write
#   actions: write

jobs:
  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    permissions: 
      checks: read
      contents: write
      actions: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          MERGE_LABELS: "merge"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}